import { StyleSheet } from "@react-pdf/renderer";

export const PDF_COLORS = {
  forest: "#3F6B4B",
  forestLight: "#A8C7A1",
  solar: "#E59B3A",
  beige: "#EFE4D2",
  beigeMuted: "#F7F2E9",
  ink: "#2A2A2A",
  inkMuted: "#5C5C5C",
  inkFaint: "#8A8A8A",
  border: "#E2DDD4",
  white: "#FFFFFF",
  critical: "#C0392B",
  warning: "#D97706",
  normal: "#3F6B4B",
  rowAlt: "#FAF8F4",
} as const;

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 9,
    color: PDF_COLORS.ink,
    paddingTop: 36,
    paddingBottom: 48,
    paddingHorizontal: 40,
    backgroundColor: PDF_COLORS.white,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: PDF_COLORS.forest,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    maxWidth: "72%",
  },
  logo: {
    width: 52,
    height: 52,
    objectFit: "contain",
  },
  brandName: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.forest,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  reportTitle: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.ink,
    marginTop: 2,
  },
  farmMeta: {
    fontSize: 9,
    color: PDF_COLORS.inkMuted,
    marginTop: 4,
    lineHeight: 1.45,
  },
  headerBadge: {
    backgroundColor: PDF_COLORS.beigeMuted,
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    alignItems: "flex-end",
  },
  badgeLabel: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.inkFaint,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  badgeValue: {
    fontSize: 9,
    color: PDF_COLORS.ink,
    marginTop: 2,
  },
  section: {
    marginBottom: 18,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  sectionAccent: {
    width: 4,
    height: 18,
    backgroundColor: PDF_COLORS.forest,
    borderRadius: 2,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.forest,
  },
  sectionDesc: {
    fontSize: 8,
    color: PDF_COLORS.inkMuted,
    marginBottom: 10,
    lineHeight: 1.4,
  },
  kpiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  kpiCard: {
    width: "23%",
    minWidth: 110,
    backgroundColor: PDF_COLORS.beigeMuted,
    borderRadius: 6,
    padding: 10,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
  },
  kpiLabel: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.inkFaint,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  kpiValue: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.forest,
    marginTop: 4,
  },
  kpiUnit: {
    fontSize: 9,
    color: PDF_COLORS.inkMuted,
    fontFamily: "Helvetica",
  },
  table: {
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    borderRadius: 6,
    overflow: "hidden",
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: PDF_COLORS.forest,
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  tableHeaderCell: {
    flex: 1,
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.white,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: PDF_COLORS.border,
  },
  tableRowAlt: {
    backgroundColor: PDF_COLORS.rowAlt,
  },
  tableCell: {
    flex: 1,
    fontSize: 8,
    color: PDF_COLORS.ink,
  },
  tableCellBold: {
    flex: 1,
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.ink,
  },
  tableCellMuted: {
    flex: 1,
    fontSize: 8,
    color: PDF_COLORS.inkMuted,
  },
  metricPairRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  metricPairCard: {
    flex: 1,
    backgroundColor: PDF_COLORS.beigeMuted,
    borderRadius: 6,
    padding: 8,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
  },
  alertCard: {
    marginBottom: 6,
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    borderLeftWidth: 4,
  },
  alertTitle: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.ink,
  },
  alertMeta: {
    fontSize: 7,
    color: PDF_COLORS.inkMuted,
    marginTop: 2,
  },
  alertSummary: {
    fontSize: 8,
    color: PDF_COLORS.ink,
    marginTop: 4,
    lineHeight: 1.4,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: PDF_COLORS.border,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 7,
    color: PDF_COLORS.inkFaint,
  },
  footerBrand: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: PDF_COLORS.forest,
  },
  introBox: {
    backgroundColor: PDF_COLORS.beigeMuted,
    borderRadius: 6,
    padding: 12,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: PDF_COLORS.solar,
  },
  introText: {
    fontSize: 9,
    color: PDF_COLORS.inkMuted,
    lineHeight: 1.5,
  },
});
