quarkus.application.name=terranova-api
quarkus.http.port=8080

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.path=/q/swagger-ui

# Configuracoes reais de CORS e Oracle entram nas proximas etapas.
